/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorLogin;
import Controlador.ControladorProducto;
import Controlador.ControladorProveedor;
import Modelo.LoginDAO;
import Modelo.ProductoDAO;
import Modelo.ProveedorDAO;
import javax.swing.JFrame;

public class FrmSistema extends javax.swing.JFrame {

    /**
     * Creates new form SistemaViveresDanielito
     */
    public FrmSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuStock = new javax.swing.JMenu();
        menuAñadir = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenuItem();
        menuINOUT = new javax.swing.JMenu();
        menuEntrada = new javax.swing.JMenuItem();
        menuSalidas = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido al Sistema de");

        jLabel2.setText("Víveres Danielito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        menuStock.setText("Gestión de Productos");
        menuStock.setActionCommand("Stock");

        menuAñadir.setText("Añadir Producto Nuevo");
        menuAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAñadirActionPerformed(evt);
            }
        });
        menuStock.add(menuAñadir);

        menuModificar.setText("Gestionar Productos Existentes");
        menuStock.add(menuModificar);

        menuPrincipal.add(menuStock);

        menuINOUT.setText("Entradas/Salidas");

        menuEntrada.setText("Ingreso Productos");
        menuINOUT.add(menuEntrada);

        menuSalidas.setText("Salida Productos");
        menuINOUT.add(menuSalidas);

        menuPrincipal.add(menuINOUT);

        menuReportes.setText("Generar Reporte");

        menuVentas.setText("Reporte de ventas");
        menuReportes.add(menuVentas);

        menuInventario.setText("Reporte inventario");
        menuReportes.add(menuInventario);

        menuPrincipal.add(menuReportes);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAñadirActionPerformed
        // TODO add your handling code here:
        FrmProducto vistaAgProd = new FrmProducto();
            vistaAgProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ProductoDAO daoProducto = new ProductoDAO();
    ProveedorDAO daoProveedor=new ProveedorDAO();
    ControladorProducto controladorProducto = new ControladorProducto(vistaAgProd, daoProducto);
    vistaAgProd.setVisible(true);
    vistaAgProd.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {

        @Override
        public void run() {

            FrmLogin vistaLogin = new FrmLogin();

            LoginDAO daoLogin = new LoginDAO();

            ControladorLogin controladorLogin =
                    new ControladorLogin(vistaLogin, daoLogin);

            vistaLogin.setVisible(true);

            vistaLogin.setLocationRelativeTo(null);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAñadir;
    private javax.swing.JMenuItem menuEntrada;
    private javax.swing.JMenu menuINOUT;
    private javax.swing.JMenuItem menuInventario;
    private javax.swing.JMenuItem menuModificar;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuSalidas;
    private javax.swing.JMenu menuStock;
    private javax.swing.JMenuItem menuVentas;
    // End of variables declaration//GEN-END:variables
}
