/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorGestionInventarioo;
import Controlador.ControladorProducto;
import Modelo.ProductoDAO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Lenovo
 */

public class FrmGestionProductos extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionProductos
     */
       int xMouse, yMouse; 
    public FrmGestionProductos() {
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent e) {
        System.out.println("FrmGestionProductos se está cerrando");
    }

   
    
    @Override
    public void windowClosed(java.awt.event.WindowEvent e) {
        System.out.println("FrmGestionProductos se cerró");
    }
});
        
    SetImageLabel(agregar, "src/imagenes/agregar.png");
        SetImageLabel(agregarblanco, "src/imagenes/agregarblanco.png");
        agregarblanco.setVisible(false);
        SetImageLabel(usuario, "src/imagenes/usuarioblanco.png");
        SetImageLabel(logo, "src/imagenes/logoblanco.png");
        SetImageLabel(entrada, "src/imagenes/entradaysalida.png");
        SetImageLabel(entradablanco, "src/imagenes/entradaysalidablanco.png");
        entradablanco.setVisible(false);
        SetImageLabel(gestion, "src/imagenes/gestionar.png");
        SetImageLabel(gestionblanco, "src/imagenes/gestionarblanco.png");
        gestionblanco.setVisible(false);
        SetImageLabel(reportes, "src/imagenes/reportes.png");
        SetImageLabel(reportesblanco, "src/imagenes/reportesblanco.png");
        reportesblanco.setVisible(false);
        SetImageLabel(salir, "src/imagenes/cerrarsesion.png");
        SetImageLabel(salirblanco, "src/imagenes/cerrarsesionblanco.png");
        salirblanco.setVisible(false);     
        jLabel6.setVisible(false);
        
        btnBuscar.setVisible(false);
        txtBuscar.setVisible(false);
    }

    
    private void SetImageLabel(JLabel logo, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icon);
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menu = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        gestion = new javax.swing.JLabel();
        entrada = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        txtSalir1 = new javax.swing.JLabel();
        txtGestion = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JLabel();
        txtReporte = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JLabel();
        salirblanco = new javax.swing.JLabel();
        agregarblanco = new javax.swing.JLabel();
        gestionblanco = new javax.swing.JLabel();
        entradablanco = new javax.swing.JLabel();
        reportesblanco = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        logo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1009, 670));
        setMinimumSize(new java.awt.Dimension(1009, 670));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 38, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1009, 670));
        jPanel1.setMinimumSize(new java.awt.Dimension(1009, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(1009, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 223, 255));
        jLabel6.setText("Gestión de Productos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 255, 344, 0));

        menu.setBackground(new java.awt.Color(153, 190, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestion.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entrada.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportes.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPreferredSize(new java.awt.Dimension(30, 30));
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });
        menu.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtSalir1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtSalir1.setForeground(new java.awt.Color(0, 0, 0));
        txtSalir1.setText("Salir del Sistema");
        txtSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalir1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSalir1MousePressed(evt);
            }
        });
        menu.add(txtSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 390, -1, 30));

        txtGestion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtGestion.setForeground(new java.awt.Color(0, 0, 0));
        txtGestion.setText("       Gestión Productos");
        txtGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtGestionMouseExited(evt);
            }
        });
        menu.add(txtGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 230, 30));

        txtEntrada.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtEntrada.setForeground(new java.awt.Color(0, 0, 0));
        txtEntrada.setText("        Gestión Inventario");
        txtEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEntradaMouseExited(evt);
            }
        });
        menu.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, -1));

        txtReporte.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtReporte.setForeground(new java.awt.Color(0, 0, 0));
        txtReporte.setText("        Generar Reportes");
        txtReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReporteMouseExited(evt);
            }
        });
        menu.add(txtReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 180, 230, 20));

        txtAgregar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(0, 0, 0));
        txtAgregar.setText("      Agregar Productos");
        txtAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAgregarMouseExited(evt);
            }
        });
        menu.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 220, 30));

        salirblanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        salirblanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirblancoKeyPressed(evt);
            }
        });
        menu.add(salirblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        menu.add(agregarblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestionblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestionblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entradablanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entradablanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportesblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportesblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 430));

        usuario.setBackground(new java.awt.Color(153, 190, 255));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 110, 120));

        header.setBackground(new java.awt.Color(0, 38, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 38, 102));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        txtSalir.setBackground(new java.awt.Color(0, 38, 102));
        txtSalir.setFont(new java.awt.Font("Roboto Condensed Black", 0, 24)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 946, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setMaximumSize(new java.awt.Dimension(81, 27));
        btnModificar.setMinimumSize(new java.awt.Dimension(81, 27));
        btnModificar.setPreferredSize(new java.awt.Dimension(81, 27));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 170, 40));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEliminarKeyPressed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 170, 40));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        jScrollPane1.setForeground(new java.awt.Color(153, 190, 255));
        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N

        tablaProductos.setBackground(new java.awt.Color(153, 190, 255));
        tablaProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tablaProductos.setForeground(new java.awt.Color(0, 0, 0));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaProductos.setFillsViewportHeight(true);
        tablaProductos.setGridColor(new java.awt.Color(153, 190, 255));
        tablaProductos.setSelectionForeground(new java.awt.Color(82, 126, 204));
        jScrollPane1.setViewportView(tablaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 710, 380));

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 140));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, 20));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        System.exit(0);
    }//GEN-LAST:event_salirKeyPressed

    private void txtSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalir1MouseClicked

    private void txtSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseEntered
        txtSalir1.setForeground(Color.white);
        salir.setVisible(false);
        salirblanco.setVisible(true);
    }//GEN-LAST:event_txtSalir1MouseEntered

    private void txtSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseExited
        txtSalir1.setForeground(Color.black);
        salirblanco.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_txtSalir1MouseExited

    private void txtSalir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MousePressed

    }//GEN-LAST:event_txtSalir1MousePressed

    private void txtGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseClicked
       
    }//GEN-LAST:event_txtGestionMouseClicked

    private void txtGestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseEntered
        txtGestion.setForeground(Color.white);
        gestion.setVisible(false);
        gestionblanco.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseEntered

    private void txtGestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseExited
        txtGestion.setForeground(Color.black);
        gestionblanco.setVisible(false);
        gestion.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseExited

    private void txtEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseClicked
        FrmGestionInventarioo vistaGestInv = new FrmGestionInventarioo();
        vistaGestInv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorGestionInventarioo(vistaGestInv, daoProducto);
        vistaGestInv.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(false);
            }
        });
        vistaGestInv.setVisible(true);
        vistaGestInv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtEntradaMouseClicked

    private void txtEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseEntered
        txtEntrada.setForeground(Color.white);
        entrada.setVisible(false);
        entradablanco.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseEntered

    private void txtEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseExited
        txtEntrada.setForeground(Color.black);
        entradablanco.setVisible(false);
        entrada.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseExited

    private void txtReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseClicked
        Vista.FrmGenerarReporte vista = new Vista.FrmGenerarReporte();
        Modelo.MovimientoDAO movDao = new Modelo.MovimientoDAO();
        Modelo.ProductoDAO prodDao = new Modelo.ProductoDAO();
        new Controlador.ControladorGenerarReporte(vista, movDao, prodDao);
        vista.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        vista.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(false);
            }
        });
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtReporteMouseClicked

    private void txtReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseEntered
        txtReporte.setForeground(Color.white);
        reportes.setVisible(false);
        reportesblanco.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseEntered

    private void txtReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseExited
        txtReporte.setForeground(Color.black);
        reportesblanco.setVisible(false);
        reportes.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseExited

    private void txtAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseClicked
        FrmProducto vistaAgProd = new FrmProducto();
            vistaAgProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ProductoDAO daoProducto = new ProductoDAO();
    new ControladorProducto(vistaAgProd, daoProducto);
    vistaAgProd.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            new FrmSistema().setVisible(false);
        }
    });
    vistaAgProd.setVisible(true);
    vistaAgProd.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_txtAgregarMouseClicked

    private void txtAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseEntered
        txtAgregar.setForeground(Color.white);
        agregar.setVisible(false);
        agregarblanco.setVisible(true);
    }//GEN-LAST:event_txtAgregarMouseEntered

    private void txtAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseExited
        txtAgregar.setForeground(Color.black);
        agregar.setVisible(true);
        agregarblanco.setVisible(false);
    }//GEN-LAST:event_txtAgregarMouseExited

    private void salirblancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirblancoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirblancoKeyPressed

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited

        int rgb = Color.HSBtoRGB(217 / 360f, 100 / 100f, 40 / 100f);
        btnSalir.setBackground(new Color(rgb));
    }//GEN-LAST:event_txtSalirMouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        btnModificar.setBackground(new Color(82,126,204));
        btnModificar.setForeground(Color.white);
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        btnModificar.setBackground(Color.white);
        btnModificar.setForeground(Color.black);
    }//GEN-LAST:event_btnModificarMouseExited

    private void btnEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarKeyPressed

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(82,126,204));
        btnEliminar.setForeground(Color.white);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
         btnEliminar.setBackground(Color.white);
        btnEliminar.setForeground(Color.black);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked

    }//GEN-LAST:event_btnModificarMouseClicked

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        FrmSistema frmSistema = new FrmSistema();
frmSistema.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
frmSistema.setVisible(true);
frmSistema.setLocationRelativeTo(null);
this.dispose();
    }//GEN-LAST:event_logoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionProductos().setVisible(true);
            }
        });
    }

    public JTable getTablaProductos() {
    return tablaProductos;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel agregarblanco;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel entrada;
    private javax.swing.JLabel entradablanco;
    private javax.swing.JLabel gestion;
    private javax.swing.JLabel gestionblanco;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel reportesblanco;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel salirblanco;
    public javax.swing.JTable tablaProductos;
    private javax.swing.JLabel txtAgregar;
    public javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtEntrada;
    private javax.swing.JLabel txtGestion;
    private javax.swing.JLabel txtReporte;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel txtSalir1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
