/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorGestionInventarioo;
import Controlador.ControladorGestionP;
import Controlador.ControladorProducto;
import Modelo.ProductoDAO;
import Modelo.Producto;
import java.awt.Color;
import javax.swing.JFrame;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class FrmProducto extends javax.swing.JFrame {
    
        
    /**
     * Creates new form FrmProducto
     */
    int xMouse, yMouse; 
    public FrmProducto() {
        initComponents();
        paralasventanas();
        
        SetImageLabel(agregar, "/imagenes/agregar.png");
        SetImageLabel(agregarblanco, "/imagenes/agregarblanco.png");
        agregarblanco.setVisible(false);
        SetImageLabel(usuario, "/imagenes/usuarioblanco.png");
        SetImageLabel(logo, "/imagenes/logoblanco.png");
        SetImageLabel(entrada, "/imagenes/entradaysalida.png");
        SetImageLabel(entradablanco, "/imagenes/entradaysalidablanco.png");
        entradablanco.setVisible(false);
        SetImageLabel(gestion, "/imagenes/gestionar.png");
        SetImageLabel(gestionblanco, "/imagenes/gestionarblanco.png");
        gestionblanco.setVisible(false);
        SetImageLabel(reportes, "/imagenes/reportes.png");
        SetImageLabel(reportesblanco, "/imagenes/reportesblanco.png");
        reportesblanco.setVisible(false);
        SetImageLabel(salir, "/imagenes/cerrarsesion.png");
        SetImageLabel(salirblanco, "/imagenes/cerrarsesionblanco.png");
        salirblanco.setVisible(false);     
        jTextFieldCodigoProducto.setVisible(false);
        jLabel6.setVisible(false);

        // el precio no debe aceptar letras ni ningun caracter que no sea
        // un numero (con punto decimal), asi ni siquiera se puede teclear
        // algo invalido en vez de avisar recien al momento de registrar.
        FiltroNumerico.soloDecimales(txtPrecio);
    }
    
    private void paralasventanas() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    private void SetImageLabel(JLabel logo, String root){
        java.net.URL recurso = getClass().getResource(root);
        if (recurso == null) {
            System.err.println("aviso: no se encontro la imagen " + root);
            return;
        }
        ImageIcon image = new ImageIcon(recurso);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menu = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        gestion = new javax.swing.JLabel();
        entrada = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        txtSalir1 = new javax.swing.JLabel();
        txtGestion = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JLabel();
        txtReporte = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JLabel();
        salirblanco = new javax.swing.JLabel();
        agregarblanco = new javax.swing.JLabel();
        gestionblanco = new javax.swing.JLabel();
        entradablanco = new javax.swing.JLabel();
        reportesblanco = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        CmbTipo = new javax.swing.JComboBox<>();
        txtProveedor = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        header = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1009, 670));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 38, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1009, 670));
        jPanel1.setMinimumSize(new java.awt.Dimension(1009, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(1009, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Añadir Nuevo Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 255, 344, 0));

        menu.setBackground(new java.awt.Color(153, 190, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestion.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entrada.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportes.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPreferredSize(new java.awt.Dimension(30, 30));
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });
        menu.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtSalir1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtSalir1.setForeground(new java.awt.Color(0, 0, 0));
        txtSalir1.setText("Salir del Sistema");
        txtSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalir1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSalir1MousePressed(evt);
            }
        });
        menu.add(txtSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 390, 200, 30));

        txtGestion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtGestion.setForeground(new java.awt.Color(0, 0, 0));
        txtGestion.setText("       Gestión Productos");
        txtGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtGestionMouseExited(evt);
            }
        });
        menu.add(txtGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 230, 30));

        txtEntrada.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtEntrada.setForeground(new java.awt.Color(0, 0, 0));
        txtEntrada.setText("        Gestión Inventario");
        txtEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEntradaMouseExited(evt);
            }
        });
        menu.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, -1));

        txtReporte.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtReporte.setForeground(new java.awt.Color(0, 0, 0));
        txtReporte.setText("        Generar Reportes");
        txtReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReporteMouseExited(evt);
            }
        });
        menu.add(txtReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 180, 230, 20));

        txtAgregar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(0, 0, 0));
        txtAgregar.setText("      Agregar Productos");
        txtAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAgregarMouseExited(evt);
            }
        });
        menu.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 220, 30));

        salirblanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        salirblanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirblancoKeyPressed(evt);
            }
        });
        menu.add(salirblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        menu.add(agregarblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestionblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestionblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entradablanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entradablanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportesblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportesblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 430));

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 140));

        usuario.setBackground(new java.awt.Color(153, 190, 255));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 110, 120));

        jPanel2.setBackground(new java.awt.Color(153, 190, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Proveedor:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio Unitario:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Codigo de Producto");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 200, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(null);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 410, 40));

        CmbTipo.setBackground(new java.awt.Color(255, 255, 255));
        CmbTipo.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        CmbTipo.setForeground(new java.awt.Color(0, 0, 0));
        CmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Lácteos", "Limpieza", "Snacks", "Embutidos", "Carnes", "Otros", "Condimentos" }));
        CmbTipo.setSelectedItem("Seleccione un tipo");
        CmbTipo.setToolTipText("seleccionar");
        CmbTipo.setBorder(null);
        CmbTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbTipoActionPerformed(evt);
            }
        });
        jPanel2.add(CmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 410, 40));

        txtProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtProveedor.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(0, 0, 0));
        txtProveedor.setEditable(true);
        txtProveedor.setBorder(null);
        txtProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 410, 40));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBorder(null);
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 410, 40));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 170, 50));

        jTextFieldCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoProductoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 20, -1));

        jSeparator2.setBackground(new java.awt.Color(10, 25, 51));
        jSeparator2.setForeground(new java.awt.Color(10, 25, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 53, 410, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 710, 430));

        header.setBackground(new java.awt.Color(0, 38, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 38, 102));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        txtSalir.setBackground(new java.awt.Color(0, 38, 102));
        txtSalir.setFont(new java.awt.Font("Roboto Condensed Black", 0, 24)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 946, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));
        // nota: aqui antes se agregaba un "logo1", una etiqueta fantasma sin
        // icono ni funcion que quedaba pegada justo encima del logo real
        // (mismas coordenadas). era puro sobrante, se elimino.

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorActionPerformed

    private void CmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbTipoActionPerformed

    private void jTextFieldCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoProductoActionPerformed

    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        System.exit(0);
    }//GEN-LAST:event_salirKeyPressed

    private void txtSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseClicked
    System.exit(0);
    }//GEN-LAST:event_txtSalir1MouseClicked

    private void txtSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseEntered
        txtSalir1.setForeground(Color.white);
        salir.setVisible(false);
        salirblanco.setVisible(true);
    }//GEN-LAST:event_txtSalir1MouseEntered

    private void txtSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseExited
        txtSalir1.setForeground(Color.black);
        salirblanco.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_txtSalir1MouseExited

    private void txtSalir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MousePressed
       
    }//GEN-LAST:event_txtSalir1MousePressed

    private void txtGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseClicked
        FrmGestionProductos vistaInvProd = new FrmGestionProductos();

    ProductoDAO daoProducto = new ProductoDAO();
    new ControladorGestionP(vistaInvProd, daoProducto);

    vistaInvProd.setLocationRelativeTo(null);
    vistaInvProd.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_txtGestionMouseClicked

    private void txtGestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseEntered
        txtGestion.setForeground(Color.white);
        gestion.setVisible(false);
        gestionblanco.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseEntered

    private void txtGestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseExited
        txtGestion.setForeground(Color.black);
        gestionblanco.setVisible(false);
        gestion.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseExited

    private void txtEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseClicked
        FrmGestionInventarioo vistaGestInv = new FrmGestionInventarioo();
        vistaGestInv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorGestionInventarioo(vistaGestInv, daoProducto);
        vistaGestInv.setVisible(true);
        vistaGestInv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtEntradaMouseClicked

    private void txtEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseEntered
        txtEntrada.setForeground(Color.white);
        entrada.setVisible(false);
        entradablanco.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseEntered

    private void txtEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseExited
        txtEntrada.setForeground(Color.black);
        entradablanco.setVisible(false);
        entrada.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseExited

    private void txtReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseClicked
        Vista.FrmGenerarReporte vista = new Vista.FrmGenerarReporte();
        Modelo.MovimientoDAO movDao = new Modelo.MovimientoDAO();
        Modelo.ProductoDAO prodDao = new Modelo.ProductoDAO();
        new Controlador.ControladorGenerarReporte(vista, movDao, prodDao);
        vista.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtReporteMouseClicked

    private void txtReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseEntered
        txtReporte.setForeground(Color.white);
        reportes.setVisible(false);
        reportesblanco.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseEntered

    private void txtReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseExited
        txtReporte.setForeground(Color.black);
        reportesblanco.setVisible(false);
        reportes.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseExited

    private void txtAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseClicked

    }//GEN-LAST:event_txtAgregarMouseClicked

    private void txtAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseEntered
        txtAgregar.setForeground(Color.white);
        agregar.setVisible(false);
        agregarblanco.setVisible(true);
    }//GEN-LAST:event_txtAgregarMouseEntered

    private void txtAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseExited
        txtAgregar.setForeground(Color.black);
        agregar.setVisible(true);
        agregarblanco.setVisible(false);
    }//GEN-LAST:event_txtAgregarMouseExited

    private void salirblancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirblancoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirblancoKeyPressed

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        btnRegistrar.setBackground(new Color(82,126,204));
        btnRegistrar.setForeground(Color.white);
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        btnRegistrar.setBackground(Color.white);
        btnRegistrar.setForeground(Color.black);
        
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited

        int rgb = Color.HSBtoRGB(217 / 360f, 100 / 100f, 40 / 100f);
        btnSalir.setBackground(new Color(rgb));
    }//GEN-LAST:event_txtSalirMouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        FrmSistema frmSistema = new FrmSistema();
frmSistema.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
frmSistema.setVisible(true);
frmSistema.setLocationRelativeTo(null);
this.dispose();
    }//GEN-LAST:event_logoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FrmProducto v=new FrmProducto();
        ProductoDAO pDAO=new ProductoDAO();
        new ControladorProducto(v,pDAO);
        v.setVisible(true);
        v.setLocationRelativeTo(v);

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmCosecha().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CmbTipo;
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel agregarblanco;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel entrada;
    private javax.swing.JLabel entradablanco;
    private javax.swing.JLabel gestion;
    private javax.swing.JLabel gestionblanco;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField jTextFieldCodigoProducto;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel reportesblanco;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel salirblanco;
    private javax.swing.JLabel txtAgregar;
    private javax.swing.JLabel txtEntrada;
    private javax.swing.JLabel txtGestion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JComboBox<String> txtProveedor;
    private javax.swing.JLabel txtReporte;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel txtSalir1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

}
