/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorGestionP;
import Controlador.ControladorGestionInventarioo;
import Controlador.ControladorLogin;
import Controlador.ControladorProducto;

import Modelo.LoginDAO;
import Modelo.ProductoDAO;
import Modelo.ProveedorDAO;
import javax.swing.JFrame;

public class FrmSistema extends javax.swing.JFrame {

    /**
     * Creates new form SistemaViveresDanielito
     */
    public FrmSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuStock = new javax.swing.JMenu();
        menuAñadir = new javax.swing.JMenuItem();
        menuGestorP = new javax.swing.JMenuItem();
        menuINOUT = new javax.swing.JMenu();
        menuGestorI = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuInventario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido al Sistema de");

        jLabel2.setText("Víveres Danielito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        menuStock.setText("Gestión de Productos");
        menuStock.setActionCommand("Stock");

        menuAñadir.setText("Añadir Producto Nuevo");
        menuAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAñadirActionPerformed(evt);
            }
        });
        menuStock.add(menuAñadir);

        menuGestorP.setText("Gestionar Productos Existentes");
        menuGestorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestorPActionPerformed(evt);
            }
        });
        menuStock.add(menuGestorP);

        menuPrincipal.add(menuStock);

        menuINOUT.setText("Entradas/Salidas");

        menuGestorI.setText("Gestión Inventario");
        menuGestorI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestorIActionPerformed(evt);
            }
        });
        menuINOUT.add(menuGestorI);

        menuPrincipal.add(menuINOUT);

        menuReportes.setText("Generar Reporte");

        menuInventario.setText("Reporte inventario");
        menuInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInventarioActionPerformed(evt);
            }
        });
        menuReportes.add(menuInventario);

        menuPrincipal.add(menuReportes);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAñadirActionPerformed
        // TODO add your handling code here:
        FrmProducto vistaAgProd = new FrmProducto();
            vistaAgProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ProductoDAO daoProducto = new ProductoDAO();
    new ControladorProducto(vistaAgProd, daoProducto);
    vistaAgProd.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            new FrmSistema().setVisible(true);
        }
    });
    vistaAgProd.setVisible(true);
    vistaAgProd.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_menuAñadirActionPerformed

    private void menuGestorIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestorIActionPerformed
        FrmGestionInventarioo vistaGestInv = new FrmGestionInventarioo();
        vistaGestInv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorGestionInventarioo(vistaGestInv, daoProducto);
        vistaGestInv.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(true);
            }
        });
        vistaGestInv.setVisible(true);
        vistaGestInv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuGestorIActionPerformed

    private void menuGestorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestorPActionPerformed
         FrmGestionProductos vistaInvProd = new FrmGestionProductos();
            vistaInvProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ProductoDAO daoProducto = new ProductoDAO();
    new ControladorGestionP(vistaInvProd, daoProducto);
    vistaInvProd.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            new FrmSistema().setVisible(true);
        }
    });
    vistaInvProd.setVisible(true);
    vistaInvProd.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_menuGestorPActionPerformed

    private void menuGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarReporteActionPerformed
        Vista.FrmGenerarReporte vista = new Vista.FrmGenerarReporte();
        Modelo.MovimientoDAO movDao = new Modelo.MovimientoDAO();
        Modelo.ProductoDAO prodDao = new Modelo.ProductoDAO();
        new Controlador.ControladorGenerarReporte(vista, movDao, prodDao);
        vista.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vista.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(true);
            }
        });
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuGenerarReporteActionPerformed

    private void menuInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInventarioActionPerformed
        Vista.FrmGenerarReporte vista = new Vista.FrmGenerarReporte();
        Modelo.MovimientoDAO movDao = new Modelo.MovimientoDAO();
        Modelo.ProductoDAO prodDao = new Modelo.ProductoDAO();
        new Controlador.ControladorGenerarReporte(vista, movDao, prodDao);
        vista.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        vista.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(true);
            }
        });
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuInventarioActionPerformed
                 
 
public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {

        @Override
        public void run() {

            FrmLogin vistaLogin = new FrmLogin();

            LoginDAO daoLogin = new LoginDAO();

            new ControladorLogin(vistaLogin, daoLogin);

            vistaLogin.setVisible(true);

            vistaLogin.setLocationRelativeTo(null);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAñadir;
    public javax.swing.JMenuItem menuGestorI;
    public javax.swing.JMenuItem menuGestorP;
    private javax.swing.JMenu menuINOUT;
    private javax.swing.JMenuItem menuInventario;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuStock;
    // End of variables declaration//GEN-END:variables
}
