package Vista;

import Controlador.ControladorGestionInventarioo;
import Controlador.ControladorGestionP;
import Controlador.ControladorProducto;
import Modelo.ProductoDAO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmGenerarReporte extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGenerarReporte.class.getName());

    /**
     * Creates new form FrmGenerarReporte
     */
     int xMouse, yMouse; 
    public FrmGenerarReporte() {
        initComponents();
        SetImageLabel(agregar, "src/imagenes/agregar.png");
        SetImageLabel(agregarblanco, "src/imagenes/agregarblanco.png");
        agregarblanco.setVisible(false);
        SetImageLabel(usuario, "src/imagenes/usuarioblanco.png");
        SetImageLabel(logo, "src/imagenes/logoblanco.png");
        SetImageLabel(entrada, "src/imagenes/entradaysalida.png");
        SetImageLabel(entradablanco, "src/imagenes/entradaysalidablanco.png");
        entradablanco.setVisible(false);
        SetImageLabel(gestion, "src/imagenes/gestionar.png");
        SetImageLabel(gestionblanco, "src/imagenes/gestionarblanco.png");
        gestionblanco.setVisible(false);
        SetImageLabel(reportes, "src/imagenes/reportes.png");
        SetImageLabel(reportesblanco, "src/imagenes/reportesblanco.png");
        reportesblanco.setVisible(false);
        SetImageLabel(salir, "src/imagenes/cerrarsesion.png");
        SetImageLabel(salirblanco, "src/imagenes/cerrarsesionblanco.png");
        salirblanco.setVisible(false); 
        
        jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        gestion = new javax.swing.JLabel();
        entrada = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        txtSalir1 = new javax.swing.JLabel();
        txtGestion = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JLabel();
        txtReporte = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JLabel();
        salirblanco = new javax.swing.JLabel();
        agregarblanco = new javax.swing.JLabel();
        gestionblanco = new javax.swing.JLabel();
        entradablanco = new javax.swing.JLabel();
        reportesblanco = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1GenerarreporteEspecifico = new javax.swing.JButton();
        jButton2Generarreportegeneral = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1producto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1Fechadesdde = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1fechaHasta = new javax.swing.JFormattedTextField();
        jComboBox1categoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1estado = new javax.swing.JComboBox<>();
        usuario = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 38, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1009, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generar reporte ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jButton3.setText("Menu Principal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 10, -1));

        menu.setBackground(new java.awt.Color(153, 190, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestion.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entrada.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportes.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPreferredSize(new java.awt.Dimension(30, 30));
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });
        menu.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtSalir1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtSalir1.setForeground(new java.awt.Color(0, 0, 0));
        txtSalir1.setText("Salir del Sistema");
        txtSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalir1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSalir1MousePressed(evt);
            }
        });
        menu.add(txtSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 390, 200, 30));

        txtGestion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtGestion.setForeground(new java.awt.Color(0, 0, 0));
        txtGestion.setText("       Gestión Productos");
        txtGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtGestionMouseExited(evt);
            }
        });
        menu.add(txtGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 230, 30));

        txtEntrada.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtEntrada.setForeground(new java.awt.Color(0, 0, 0));
        txtEntrada.setText("        Gestión Inventario");
        txtEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEntradaMouseExited(evt);
            }
        });
        menu.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, -1));

        txtReporte.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtReporte.setForeground(new java.awt.Color(0, 0, 0));
        txtReporte.setText("        Generar Reportes");
        txtReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReporteMouseExited(evt);
            }
        });
        menu.add(txtReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 180, 230, 20));

        txtAgregar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(0, 0, 0));
        txtAgregar.setText("      Agregar Productos");
        txtAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAgregarMouseExited(evt);
            }
        });
        menu.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 220, 30));

        salirblanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        salirblanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirblancoKeyPressed(evt);
            }
        });
        menu.add(salirblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        menu.add(agregarblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestionblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestionblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entradablanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entradablanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportesblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportesblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 430));

        jPanel2.setBackground(new java.awt.Color(153, 190, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1GenerarreporteEspecifico.setBackground(new java.awt.Color(255, 255, 255));
        jButton1GenerarreporteEspecifico.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jButton1GenerarreporteEspecifico.setForeground(new java.awt.Color(0, 0, 0));
        jButton1GenerarreporteEspecifico.setText("Generar Reporte Especifico ");
        jButton1GenerarreporteEspecifico.setBorder(null);
        jButton1GenerarreporteEspecifico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1GenerarreporteEspecifico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1GenerarreporteEspecificoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1GenerarreporteEspecificoMouseExited(evt);
            }
        });
        jPanel2.add(jButton1GenerarreporteEspecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 310, 40));

        jButton2Generarreportegeneral.setBackground(new java.awt.Color(255, 255, 255));
        jButton2Generarreportegeneral.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jButton2Generarreportegeneral.setForeground(new java.awt.Color(0, 0, 0));
        jButton2Generarreportegeneral.setText("Generar Reporte General");
        jButton2Generarreportegeneral.setBorder(null);
        jButton2Generarreportegeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2Generarreportegeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2GenerarreportegeneralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2GenerarreportegeneralMouseExited(evt);
            }
        });
        jPanel2.add(jButton2Generarreportegeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 300, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jComboBox1producto.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1producto.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jComboBox1producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1producto.setBorder(null);
        jComboBox1producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jComboBox1producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha desde ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        jFormattedTextField1Fechadesdde.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1Fechadesdde.setBorder(null);
        jFormattedTextField1Fechadesdde.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedTextField1Fechadesdde.setText("DD/MM/AA");
        jFormattedTextField1Fechadesdde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1FechadesddeActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextField1Fechadesdde, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha Hasta");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, -1));

        jFormattedTextField1fechaHasta.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1fechaHasta.setBorder(null);
        jFormattedTextField1fechaHasta.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedTextField1fechaHasta.setText("DD/MM/AA");
        jPanel2.add(jFormattedTextField1fechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 300, 30));

        jComboBox1categoria.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1categoria.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jComboBox1categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1categoria.setBorder(null);
        jComboBox1categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jComboBox1categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 300, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Categoria ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estado");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 70, -1));

        jComboBox1estado.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1estado.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jComboBox1estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1estado.setBorder(null);
        jComboBox1estado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jComboBox1estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 300, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 710, 430));

        usuario.setBackground(new java.awt.Color(153, 190, 255));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 110, 120));

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 140));

        header.setBackground(new java.awt.Color(0, 38, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 38, 102));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        txtSalir.setBackground(new java.awt.Color(0, 38, 102));
        txtSalir.setFont(new java.awt.Font("Roboto Condensed Black", 0, 24)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 946, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetImageLabel(JLabel logo, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icon);
        this.repaint();
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        System.exit(0);
    }//GEN-LAST:event_salirKeyPressed

    private void txtSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalir1MouseClicked

    private void txtSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseEntered
        txtSalir1.setForeground(Color.white);
        salir.setVisible(false);
        salirblanco.setVisible(true);
    }//GEN-LAST:event_txtSalir1MouseEntered

    private void txtSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseExited
        txtSalir1.setForeground(Color.black);
        salirblanco.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_txtSalir1MouseExited

    private void txtSalir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MousePressed

    }//GEN-LAST:event_txtSalir1MousePressed

    private void txtGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseClicked
        FrmGestionProductos vistaInvProd = new FrmGestionProductos();

        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorGestionP(vistaInvProd, daoProducto);

        vistaInvProd.setLocationRelativeTo(null);
        vistaInvProd.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_txtGestionMouseClicked

    private void txtGestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseEntered
        txtGestion.setForeground(Color.white);
        gestion.setVisible(false);
        gestionblanco.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseEntered

    private void txtGestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseExited
        txtGestion.setForeground(Color.black);
        gestionblanco.setVisible(false);
        gestion.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseExited

    private void txtEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseClicked
        FrmGestionInventarioo vistaGestInv = new FrmGestionInventarioo();
        vistaGestInv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorGestionInventarioo(vistaGestInv, daoProducto);
        vistaGestInv.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(false);
            }
        });
        vistaGestInv.setVisible(true);
        vistaGestInv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtEntradaMouseClicked

    private void txtEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseEntered
        txtEntrada.setForeground(Color.white);
        entrada.setVisible(false);
        entradablanco.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseEntered

    private void txtEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseExited
        txtEntrada.setForeground(Color.black);
        entradablanco.setVisible(false);
        entrada.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseExited

    private void txtReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseClicked
        
    }//GEN-LAST:event_txtReporteMouseClicked

    private void txtReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseEntered
        txtReporte.setForeground(Color.white);
        reportes.setVisible(false);
        reportesblanco.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseEntered

    private void txtReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseExited
        txtReporte.setForeground(Color.black);
        reportesblanco.setVisible(false);
        reportes.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseExited

    private void txtAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseClicked
FrmProducto vistaAgProd = new FrmProducto();
        vistaAgProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorProducto(vistaAgProd, daoProducto);
        vistaAgProd.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(false);
            }
        });
        vistaAgProd.setVisible(true);
        vistaAgProd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtAgregarMouseClicked

    private void txtAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseEntered
        txtAgregar.setForeground(Color.white);
        agregar.setVisible(false);
        agregarblanco.setVisible(true);
    }//GEN-LAST:event_txtAgregarMouseEntered

    private void txtAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseExited
        txtAgregar.setForeground(Color.black);
        agregar.setVisible(true);
        agregarblanco.setVisible(false);
    }//GEN-LAST:event_txtAgregarMouseExited

    private void salirblancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirblancoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirblancoKeyPressed

    private void jFormattedTextField1FechadesddeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1FechadesddeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1FechadesddeActionPerformed

    private void jButton1GenerarreporteEspecificoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1GenerarreporteEspecificoMouseEntered
        jButton1GenerarreporteEspecifico.setBackground(new Color(82,126,204));
        jButton1GenerarreporteEspecifico.setForeground(Color.white);
    }//GEN-LAST:event_jButton1GenerarreporteEspecificoMouseEntered

    private void jButton1GenerarreporteEspecificoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1GenerarreporteEspecificoMouseExited
        jButton1GenerarreporteEspecifico.setBackground(Color.white);
       jButton1GenerarreporteEspecifico.setForeground(Color.black);
    }//GEN-LAST:event_jButton1GenerarreporteEspecificoMouseExited

    private void jButton2GenerarreportegeneralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2GenerarreportegeneralMouseEntered
        jButton2Generarreportegeneral.setBackground(new Color(82,126,204));
        jButton2Generarreportegeneral.setForeground(Color.white);
    }//GEN-LAST:event_jButton2GenerarreportegeneralMouseEntered

    private void jButton2GenerarreportegeneralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2GenerarreportegeneralMouseExited
        jButton2Generarreportegeneral.setBackground(Color.white);
       jButton2Generarreportegeneral.setForeground(Color.black);
    }//GEN-LAST:event_jButton2GenerarreportegeneralMouseExited

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited

        int rgb = Color.HSBtoRGB(217 / 360f, 100 / 100f, 40 / 100f);
        btnSalir.setBackground(new Color(rgb));
    }//GEN-LAST:event_txtSalirMouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        FrmSistema frmSistema = new FrmSistema();
frmSistema.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
frmSistema.setVisible(true);
frmSistema.setLocationRelativeTo(null);
this.dispose();
    }//GEN-LAST:event_logoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGenerarReporte().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel agregarblanco;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel entrada;
    private javax.swing.JLabel entradablanco;
    private javax.swing.JLabel gestion;
    private javax.swing.JLabel gestionblanco;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1GenerarreporteEspecifico;
    private javax.swing.JButton jButton2Generarreportegeneral;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1categoria;
    private javax.swing.JComboBox<String> jComboBox1estado;
    private javax.swing.JComboBox<String> jComboBox1producto;
    private javax.swing.JFormattedTextField jFormattedTextField1Fechadesdde;
    private javax.swing.JFormattedTextField jFormattedTextField1fechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel reportesblanco;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel salirblanco;
    private javax.swing.JLabel txtAgregar;
    private javax.swing.JLabel txtEntrada;
    private javax.swing.JLabel txtGestion;
    private javax.swing.JLabel txtReporte;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel txtSalir1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

    // Public accessors for controller use (do not modify form layout)
    // Placed outside of the generated section so NetBeans won't overwrite them.
    public javax.swing.JComboBox<String> getProductoCombo() { return jComboBox1producto; }
    public javax.swing.JComboBox<String> getCategoriaCombo() { return jComboBox1categoria; }
    public javax.swing.JComboBox<String> getEstadoCombo() { return jComboBox1estado; }
    public javax.swing.JFormattedTextField getFechaDesdeField() { return jFormattedTextField1Fechadesdde; }
    public javax.swing.JFormattedTextField getFechaHastaField() { return jFormattedTextField1fechaHasta; }
    public javax.swing.JButton getButtonGenerarEspecifico() { return jButton1GenerarreporteEspecifico; }
    public javax.swing.JButton getButtonGenerarGeneral() { return jButton2Generarreportegeneral; }

}
