/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorGestionP;
import Controlador.ControladorGestionInventarioo;
import Controlador.ControladorLogin;
import Controlador.ControladorProducto;

import Modelo.LoginDAO;
import Modelo.ProductoDAO;
import Modelo.ProveedorDAO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

public class FrmSistema extends javax.swing.JFrame {

    /**
     * Creates new form SistemaViveresDanielito
     */
    int xMouse, yMouse; 
    public FrmSistema() {
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(agregar, "src/imagenes/agregar.png");
        SetImageLabel(agregarblanco, "src/imagenes/agregarblanco.png");
        agregarblanco.setVisible(false);
        SetImageLabel(usuario, "src/imagenes/usuarioblanco.png");
        SetImageLabel(logo, "src/imagenes/logoblanco.png");
        SetImageLabel(entrada, "src/imagenes/entradaysalida.png");
        SetImageLabel(entradablanco, "src/imagenes/entradaysalidablanco.png");
        entradablanco.setVisible(false);
        SetImageLabel(gestion, "src/imagenes/gestionar.png");
        SetImageLabel(gestionblanco, "src/imagenes/gestionarblanco.png");
        gestionblanco.setVisible(false);
        SetImageLabel(reportes, "src/imagenes/reportes.png");
        SetImageLabel(reportesblanco, "src/imagenes/reportesblanco.png");
        reportesblanco.setVisible(false);
        SetImageLabel(salir, "src/imagenes/cerrarsesion.png");
        SetImageLabel(salirblanco, "src/imagenes/cerrarsesionblanco.png");
        salirblanco.setVisible(false);
        SetImageLabel(productos, "src/imagenes/producto.png");
        SetImageLabel(proveedores, "src/imagenes/camion.png");
        SetImageLabel(categoria, "src/imagenes/etiqueta.png");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        gestion = new javax.swing.JLabel();
        entrada = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        txtSalir = new javax.swing.JLabel();
        txtGestion = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JLabel();
        txtReporte = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JLabel();
        salirblanco = new javax.swing.JLabel();
        agregarblanco = new javax.swing.JLabel();
        gestionblanco = new javax.swing.JLabel();
        entradablanco = new javax.swing.JLabel();
        reportesblanco = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtProductos = new javax.swing.JLabel();
        productos = new javax.swing.JLabel();
        txtProduc = new javax.swing.JLabel();
        panelProveedores = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtProveedores = new javax.swing.JLabel();
        txtProveed1 = new javax.swing.JLabel();
        proveedores = new javax.swing.JLabel();
        panelCategorias = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtCategorias = new javax.swing.JLabel();
        txtProveed = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        txtSalir1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 38, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(153, 190, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestion.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entrada.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportes.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPreferredSize(new java.awt.Dimension(30, 30));
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });
        menu.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtSalir.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(0, 0, 0));
        txtSalir.setText("      Salir del sistema");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSalirMousePressed(evt);
            }
        });
        menu.add(txtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 390, 200, 30));

        txtGestion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtGestion.setForeground(new java.awt.Color(0, 0, 0));
        txtGestion.setText("       Gestión Productos");
        txtGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtGestionMouseExited(evt);
            }
        });
        menu.add(txtGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 230, 30));

        txtEntrada.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtEntrada.setForeground(new java.awt.Color(0, 0, 0));
        txtEntrada.setText("        Gestión Inventario");
        txtEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEntradaMouseExited(evt);
            }
        });
        menu.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, -1));

        txtReporte.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtReporte.setForeground(new java.awt.Color(0, 0, 0));
        txtReporte.setText("        Generar Reportes");
        txtReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReporteMouseExited(evt);
            }
        });
        menu.add(txtReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 180, 230, 20));

        txtAgregar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(0, 0, 0));
        txtAgregar.setText("      Agregar Productos");
        txtAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAgregarMouseExited(evt);
            }
        });
        menu.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 220, 30));

        salirblanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        salirblanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirblancoKeyPressed(evt);
            }
        });
        menu.add(salirblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        menu.add(agregarblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestionblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestionblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entradablanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entradablanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportesblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportesblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 430));

        panelProductos.setBackground(new java.awt.Color(153, 190, 255));
        panelProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        panelProductos.setPreferredSize(new java.awt.Dimension(235, 400));
        panelProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 190, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));

        txtProductos.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtProductos.setForeground(new java.awt.Color(0, 0, 0));
        txtProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProductos.setText(" Productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        panelProductos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 80));
        panelProductos.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 150));

        txtProduc.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtProduc.setForeground(new java.awt.Color(0, 0, 0));
        txtProduc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProduc.setText("<html>Productos<br>Registrados</html>");
        panelProductos.add(txtProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, -1));

        jPanel1.add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 230, 400));

        panelProveedores.setBackground(new java.awt.Color(153, 190, 255));
        panelProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        panelProveedores.setPreferredSize(new java.awt.Dimension(210, 400));
        panelProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 190, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));

        txtProveedores.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtProveedores.setForeground(new java.awt.Color(0, 0, 0));
        txtProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProveedores.setText("Proveedores");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtProveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        panelProveedores.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 80));

        txtProveed1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtProveed1.setForeground(new java.awt.Color(0, 0, 0));
        txtProveed1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProveed1.setText("<html>Proveedores<br>Registrados</html>");
        panelProveedores.add(txtProveed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, -1));
        panelProveedores.add(proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 150));

        jPanel1.add(panelProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 230, 400));

        panelCategorias.setBackground(new java.awt.Color(153, 190, 255));
        panelCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        panelCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 190, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        txtCategorias.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtCategorias.setForeground(new java.awt.Color(0, 0, 0));
        txtCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCategorias.setText("Categorías");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        panelCategorias.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 80));

        txtProveed.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtProveed.setForeground(new java.awt.Color(0, 0, 0));
        txtProveed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProveed.setText("Categorías");
        panelCategorias.add(txtProveed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, -1));
        panelCategorias.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 130));

        jPanel1.add(panelCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 230, 400));

        jPanel2.setBackground(new java.awt.Color(153, 190, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("<html>Bienvenido al sistema<br>Víveres Danielito<html>");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 470, 140));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 140));

        usuario.setBackground(new java.awt.Color(153, 190, 255));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 110, 120));

        header.setBackground(new java.awt.Color(0, 38, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 38, 102));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        txtSalir1.setBackground(new java.awt.Color(0, 38, 102));
        txtSalir1.setFont(new java.awt.Font("Roboto Condensed Black", 0, 24)); // NOI18N
        txtSalir1.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir1.setText("X");
        txtSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalir1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 946, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1010, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarReporteActionPerformed
        Vista.FrmGenerarReporte vista = new Vista.FrmGenerarReporte();
        Modelo.MovimientoDAO movDao = new Modelo.MovimientoDAO();
        Modelo.ProductoDAO prodDao = new Modelo.ProductoDAO();
        new Controlador.ControladorGenerarReporte(vista, movDao, prodDao);
        vista.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        vista.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(false);
            }
        });
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuGenerarReporteActionPerformed

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
             
    }//GEN-LAST:event_txtSalirMouseClicked

    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        System.exit(0);  
    }//GEN-LAST:event_salirKeyPressed

    private void txtSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMousePressed
        System.exit(0);  
    }//GEN-LAST:event_txtSalirMousePressed

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        txtSalir.setForeground(Color.white);
        salir.setVisible(false);
        salirblanco.setVisible(true);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        txtSalir.setForeground(Color.black);
        salirblanco.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_txtSalirMouseExited

    private void salirblancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirblancoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirblancoKeyPressed

    private void txtAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseEntered
        txtAgregar.setForeground(Color.white);
        agregar.setVisible(false);
        agregarblanco.setVisible(true);
    }//GEN-LAST:event_txtAgregarMouseEntered

    private void txtAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseExited
        txtAgregar.setForeground(Color.black);
        agregar.setVisible(true);
        agregarblanco.setVisible(false);
    }//GEN-LAST:event_txtAgregarMouseExited

    private void txtAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseClicked
        FrmProducto vistaAgProd = new FrmProducto();
            vistaAgProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ProductoDAO daoProducto = new ProductoDAO();
    new ControladorProducto(vistaAgProd, daoProducto);
    vistaAgProd.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            new FrmSistema().setVisible(false);
        }
    });
    vistaAgProd.setVisible(true);
    vistaAgProd.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_txtAgregarMouseClicked

    private void txtGestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseEntered
        txtGestion.setForeground(Color.white);
        gestion.setVisible(false);
        gestionblanco.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseEntered

    private void txtEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseEntered
        txtEntrada.setForeground(Color.white);
        entrada.setVisible(false);
        entradablanco.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseEntered

    private void txtReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseEntered
        txtReporte.setForeground(Color.white);
        reportes.setVisible(false);
        reportesblanco.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseEntered

    private void txtGestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseExited
        txtGestion.setForeground(Color.black);
        gestionblanco.setVisible(false);
        gestion.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseExited

    private void txtEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseExited
        txtEntrada.setForeground(Color.black);
        entradablanco.setVisible(false);
        entrada.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseExited

    private void txtReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseExited
        txtReporte.setForeground(Color.black);
        reportesblanco.setVisible(false);
        reportes.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseExited

    private void txtGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseClicked
        FrmGestionProductos vistaInvProd = new FrmGestionProductos();
        vistaInvProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorGestionP(vistaInvProd, daoProducto);
        vistaInvProd.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(true);
            }
        });
        vistaInvProd.setVisible(true);
        vistaInvProd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtGestionMouseClicked

    private void txtEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseClicked
        FrmGestionInventarioo vistaGestInv = new FrmGestionInventarioo();
        vistaGestInv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorGestionInventarioo(vistaGestInv, daoProducto);
        vistaGestInv.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(false);
            }
        });
        vistaGestInv.setVisible(true);
        vistaGestInv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtEntradaMouseClicked

    private void txtReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseClicked
        Vista.FrmGenerarReporte vista = new Vista.FrmGenerarReporte();
        Modelo.MovimientoDAO movDao = new Modelo.MovimientoDAO();
        Modelo.ProductoDAO prodDao = new Modelo.ProductoDAO();
        new Controlador.ControladorGenerarReporte(vista, movDao, prodDao);
        vista.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        vista.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                new FrmSistema().setVisible(false);
            }
        });
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtReporteMouseClicked

    private void txtSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalir1MouseClicked

    private void txtSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_txtSalir1MouseEntered

    private void txtSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseExited

        int rgb = Color.HSBtoRGB(217 / 360f, 100 / 100f, 40 / 100f);
        btnSalir.setBackground(new Color(rgb));
    }//GEN-LAST:event_txtSalir1MouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed
                 
 
public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {

        @Override
        public void run() {

            FrmLogin vistaLogin = new FrmLogin();

            LoginDAO daoLogin = new LoginDAO();

            new ControladorLogin(vistaLogin, daoLogin);

            vistaLogin.setVisible(true);

            vistaLogin.setLocationRelativeTo(null);
        }
    });
}

private void SetImageLabel(JLabel agregar, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(agregar.getWidth(), agregar.getHeight(), Image.SCALE_DEFAULT));
        agregar.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel agregarblanco;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel entrada;
    private javax.swing.JLabel entradablanco;
    private javax.swing.JLabel gestion;
    private javax.swing.JLabel gestionblanco;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JLabel productos;
    private javax.swing.JLabel proveedores;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel reportesblanco;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel salirblanco;
    private javax.swing.JLabel txtAgregar;
    private javax.swing.JLabel txtCategorias;
    private javax.swing.JLabel txtEntrada;
    private javax.swing.JLabel txtGestion;
    private javax.swing.JLabel txtProduc;
    private javax.swing.JLabel txtProductos;
    private javax.swing.JLabel txtProveed;
    private javax.swing.JLabel txtProveed1;
    private javax.swing.JLabel txtProveedores;
    private javax.swing.JLabel txtReporte;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel txtSalir1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
