package Vista;

import Controlador.ControladorGestionInventarioo;
import Controlador.ControladorGestionP;
import Controlador.ControladorProducto;
import Modelo.Producto;
import Modelo.ProductoDAO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmEditaPrduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEditaPrduct.class.getName());
    private ProductoDAO dao;
    private String originalNombre;
    private Runnable onSave;
    private final Modelo.ProveedorDAO proveedorDao = new Modelo.ProveedorDAO();
    private final Modelo.CategoriaDAO categoriaDao = new Modelo.CategoriaDAO();
    private final java.util.ArrayList<String> proveedoresConocidos = new java.util.ArrayList<>();

    /**
     * Creates new form FrmEditaPrduct
     */
     int xMouse, yMouse; 
    public FrmEditaPrduct() {
        initComponents();
        // nota: aqui antes se volvian a crear "jLabelCodigoProducto" y
        // "jTextFieldCodigoProducto" desde cero (con "new"), pisando a los
        // que initComponents() ya habia creado y agregado a los paneles.
        // esos objetos nuevos quedaban sueltos, sin agregarse a ningun
        // panel, asi que llamarles setVisible(false) no hacia nada de
        // nada. era codigo muerto y confuso, se elimino.
    }

    
    
    public FrmEditaPrduct(Producto producto, ProductoDAO dao, Runnable onSave) {
        initComponents();
        this.dao = dao;
        this.onSave = onSave;
        // ojo: antes esta ventana nunca le ponia el icono al logo (se
        // quedaba en blanco), aqui se arregla para que se vea igual que
        // en el resto de pantallas de la app.
        SetImageLabel(logo, "/imagenes/logoblanco.png");
        SetImageLabel(usuario, "/imagenes/usuarioblanco.png");
        cargarProveedores();
        FiltroNumerico.soloDecimales(jTextFieldPrecioUnitario);
        FiltroNumerico.soloEnteros(jTextFieldStock);
        // cargar categorias dinamicas desde mongo para que el combo
        // tenga las mismas que la pantalla de agregar productos
        categoriaDao.inicializarSiVacia();
        cargarCategorias();
        cargarProducto(producto);
        setLocationRelativeTo(null);
    }

    
    
    
    private void SetImageLabel(JLabel label, String root) {
        // antes cada ventana tenia su propio metodo de escalar y todos eran
        // copias del mismo codigo. ahora centralizamos en ImagenUtil.poner
        // que ademas usa escalado por pasos para que los iconos queden mas
        // nitidos, y resuelve el bug de getWidth()==0 antes de pintarse.
        Util.ImagenUtil.poner(label, root, this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelPrecioUnitario = new javax.swing.JLabel();
        jLabelMuestraNombredeproducto = new javax.swing.JLabel();
        jLabel1Nombre = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldPrecioUnitario = new javax.swing.JTextField();
        jTextFieldProveedor = new javax.swing.JComboBox<>();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelTipoStock = new javax.swing.JLabel();
        jLabelTipoProveedor = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGuardarCambios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 38, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 170, -1));

        jPanel2.setBackground(new java.awt.Color(153, 190, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        jPanel2.setForeground(new java.awt.Color(10, 25, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTipo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTipo.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipo.setText("Tipo:");
        jPanel2.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, -1));

        jLabelPrecioUnitario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPrecioUnitario.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelPrecioUnitario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrecioUnitario.setText("Precio Unitario:");
        jPanel2.add(jLabelPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, -1));

        jLabelMuestraNombredeproducto.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelMuestraNombredeproducto.setText(".");
        jLabelMuestraNombredeproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(jLabelMuestraNombredeproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 410, 40));

        jLabel1Nombre.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1Nombre.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel1Nombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1Nombre.setText("Nombre:");
        jPanel2.add(jLabel1Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 30));

        jComboBoxTipo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTipo.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo" }));
        jComboBoxTipo.setBorder(null);
        jComboBoxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 410, 40));

        jTextFieldPrecioUnitario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecioUnitario.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jTextFieldPrecioUnitario.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrecioUnitario.setText("jTextField1");
        jTextFieldPrecioUnitario.setBorder(null);
        jPanel2.add(jTextFieldPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 410, 40));

        jTextFieldProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldProveedor.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jTextFieldProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldProveedor.setEditable(false);
        jTextFieldProveedor.setBorder(null);
        jTextFieldProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jTextFieldProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 410, 40));

        jTextFieldStock.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldStock.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jTextFieldStock.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldStock.setText("jTextField1");
        jTextFieldStock.setBorder(null);
        jPanel2.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 410, 40));

        jLabelTipoStock.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTipoStock.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelTipoStock.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoStock.setText("Stock:");
        jPanel2.add(jLabelTipoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, -1));

        jLabelTipoProveedor.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTipoProveedor.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelTipoProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoProveedor.setText("Proveedor:");
        jPanel2.add(jLabelTipoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, -1));

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseExited(evt);
            }
        });
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 170, 50));

        jButtonGuardarCambios.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardarCambios.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jButtonGuardarCambios.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGuardarCambios.setText("Guardar");
        jButtonGuardarCambios.setBorder(null);
        jButtonGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGuardarCambiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonGuardarCambiosMouseExited(evt);
            }
        });
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 170, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 410, 40));

        jTextFieldCodigoProducto.setText("jTextField1");
        jPanel2.add(jTextFieldCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 420, 0, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 710, 430));

        header.setBackground(new java.awt.Color(0, 38, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 38, 102));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        txtSalir.setBackground(new java.awt.Color(0, 38, 102));
        txtSalir.setFont(new java.awt.Font("Roboto Condensed Black", 0, 24)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 946, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 140));

        usuario.setBackground(new java.awt.Color(153, 190, 255));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 110, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        System.out.println("FrmEditaPrduct.jButtonGuardarCambiosActionPerformed -> clicked");
        guardarCambios();
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // No action needed for type selection here.
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited

        int rgb = Color.HSBtoRGB(217 / 360f, 100 / 100f, 40 / 100f);
        btnSalir.setBackground(new Color(rgb));
    }//GEN-LAST:event_txtSalirMouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void jButtonGuardarCambiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosMouseEntered
        jButtonGuardarCambios.setBackground(new Color(82,126,204));
        jButtonGuardarCambios.setForeground(Color.white);
    }//GEN-LAST:event_jButtonGuardarCambiosMouseEntered

    private void jButtonGuardarCambiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosMouseExited
        jButtonGuardarCambios.setBackground(Color.white);
        jButtonGuardarCambios.setForeground(Color.black);
    }//GEN-LAST:event_jButtonGuardarCambiosMouseExited

    private void jButtonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseEntered
        jButtonCancelar.setBackground(new Color(82,126,204));
        jButtonCancelar.setForeground(Color.white);
    }//GEN-LAST:event_jButtonCancelarMouseEntered

    private void jButtonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseExited
        jButtonCancelar.setBackground(Color.white);
        jButtonCancelar.setForeground(Color.black);
    }//GEN-LAST:event_jButtonCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEditaPrduct().setVisible(true));
    }

    // este es el texto que aparece en el combo cuando todavia no se ha elegido
    // un tipo de verdad (debe coincidir con TIPO_SIN_SELECCIONAR de ControladorProducto)
    private static final String TIPO_SIN_SELECCIONAR = "Seleccione un tipo";

    /**
     * llena el combo de tipo con las categorias de mongo.
     * misma logica que en la pantalla de agregar productos para que
     * las dos pantallas siempre muestren las mismas opciones.
     */
    private void cargarCategorias() {
        jComboBoxTipo.removeAllItems();
        jComboBoxTipo.addItem(TIPO_SIN_SELECCIONAR);
        for (String cat : categoriaDao.listar()) {
            jComboBoxTipo.addItem(cat);
        }
        jComboBoxTipo.setSelectedIndex(0);
    }

    /**
     * llena el combo de proveedores con el catalogo guardado en mongo,
     * igual que el de categorias: solo se puede elegir de la lista, no
     * escribir uno nuevo (eso se hace desde Gestion de Proveedores).
     */
    private void cargarProveedores() {
        proveedoresConocidos.clear();
        proveedoresConocidos.addAll(proveedorDao.obtenerNombresProveedores());
        jTextFieldProveedor.removeAllItems();
        for (String prov : proveedoresConocidos) {
            jTextFieldProveedor.addItem(prov);
        }
    }

    private void cargarProducto(Producto producto) {
        if (producto == null) {
            return;
        }
        jLabelMuestraNombredeproducto.setText(producto.getNombre());
        try {
            jComboBoxTipo.setSelectedItem(producto.getTipo());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "no se pudo preseleccionar el tipo del producto", ex);
        }
        jTextFieldPrecioUnitario.setText(String.valueOf(producto.getPrecioUnit()));
        String proveedorActual = producto.getProveedor();
        if (proveedorActual != null && !proveedorActual.isBlank()) {
            boolean existe = false;
            for (int i = 0; i < jTextFieldProveedor.getItemCount(); i++) {
                if (proveedorActual.equalsIgnoreCase(String.valueOf(jTextFieldProveedor.getItemAt(i)))) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                // dato antiguo que no esta en el catalogo: lo agregamos para
                // que se pueda seguir viendo/editando sin perder informacion
                jTextFieldProveedor.addItem(proveedorActual);
            }
            jTextFieldProveedor.setSelectedItem(proveedorActual);
        }
        jTextFieldStock.setText(String.valueOf(producto.getStock()));
        if (jTextFieldCodigoProducto != null) {
            jTextFieldCodigoProducto.setText(producto.getCodigo() == null ? "" : producto.getCodigo());
        }
        originalNombre = producto.getNombre();
    }

    private void guardarCambios() {
        if (dao == null) {
            // esto solo pasaria si alguien usa el constructor vacio de esta
            // ventana fuera del flujo normal de la app (ese constructor es
            // solo para que netbeans pueda previsualizar el formulario)
            javax.swing.JOptionPane.showMessageDialog(this, "No hay conexión con la base de datos para guardar.");
            return;
        }

        String nombre = jLabelMuestraNombredeproducto.getText().trim();
        Object tipoSeleccionado = jComboBoxTipo.getSelectedItem();
        String tipo = tipoSeleccionado == null ? "" : tipoSeleccionado.toString();
        String precioText = jTextFieldPrecioUnitario.getText().trim().replace(',', '.');
        String proveedor;
        Object seleccionado = jTextFieldProveedor.getSelectedItem();
        proveedor = seleccionado == null ? "" : seleccionado.toString().trim();
        String stockText = jTextFieldStock.getText().trim();
        String codigo = jTextFieldCodigoProducto != null ? jTextFieldCodigoProducto.getText().trim() : "";

        if (nombre.isBlank() || precioText.isBlank() || proveedor.isBlank() || stockText.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos para guardar.");
            return;
        }

        if (tipo.isBlank() || tipo.equals(TIPO_SIN_SELECCIONAR)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un tipo de producto válido.");
            return;
        }

        double precio;
        int stock;
        try {
            precio = Double.parseDouble(precioText);
            stock = Integer.parseInt(stockText);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Precio o stock inválido. Use valores numéricos.");
            return;
        }

        if (precio <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número mayor que cero.");
            return;
        }

        if (stock < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El stock no puede ser negativo.");
            return;
        }

        // si el usuario le cambio el nombre al producto, hay que revisar que
        // ese nombre nuevo no choque con el de otro producto ya existente
        // (antes esto no se validaba y se podian terminar con dos productos
        // distintos guardados con el mismo nombre en la base de datos)
        boolean cambioDeNombre = !nombre.equalsIgnoreCase(originalNombre == null ? "" : originalNombre);
        if (cambioDeNombre && dao.existeProducto(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya existe otro producto con ese nombre.");
            return;
        }

        try {
            Modelo.Producto actualizado = new Modelo.Producto(nombre, tipo, precio, proveedor, stock, codigo);
            dao.modificarProducto(originalNombre, actualizado);
            proveedorDao.guardarSiNoExiste(proveedor);
            javax.swing.JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");
            if (onSave != null) {
                onSave.run();
            }
            dispose();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Nombre;
    private javax.swing.JLabel jLabelMuestraNombredeproducto;
    private javax.swing.JLabel jLabelPrecioUnitario;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoProveedor;
    private javax.swing.JLabel jLabelTipoStock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldCodigoProducto;
    private javax.swing.JTextField jTextFieldPrecioUnitario;
    private javax.swing.JComboBox<String> jTextFieldProveedor;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
