package Vista;

import Controlador.ControladorGestionP;
import Controlador.ControladorProducto;
import Modelo.ProductoDAO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmGestionInventarioo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionInventarioo.class.getName());

    /**
     * Creates new form FrmGestionInventarioo
     */
    int xMouse, yMouse;
    public FrmGestionInventarioo() {
        initComponents();
        javax.swing.ButtonGroup grupoMovimiento = new javax.swing.ButtonGroup();
        grupoMovimiento.add(jRadioButtonEntrada);
        grupoMovimiento.add(jRadioButtonSalida);
        jRadioButtonEntrada.setSelected(true);

        // la cantidad de un movimiento siempre tiene que ser un numero
        // entero positivo: con este modelo el spinner ya no deja bajar de
        // 1 con las flechitas, y con el filtro de abajo tampoco se puede
        // escribir una letra a mano en el cuadro de texto del spinner.
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));
        javax.swing.JComponent editorSpinner = jSpinnerCantidad.getEditor();
        if (editorSpinner instanceof javax.swing.JSpinner.DefaultEditor) {
            FiltroNumerico.soloEnteros(((javax.swing.JSpinner.DefaultEditor) editorSpinner).getTextField());
        }
        try {
            javax.swing.text.MaskFormatter formatoFecha = new javax.swing.text.MaskFormatter("##/##/####");
            formatoFecha.setPlaceholderCharacter('_');
            jFormattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatoFecha));
        } catch (java.text.ParseException ex) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo configurar formato de fecha", ex);
        }
        jFormattedTextFieldFecha.setText(new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date()));
        
        SetImageLabel(agregar, "/imagenes/agregar.png");
        SetImageLabel(agregarblanco, "/imagenes/agregarblanco.png");
        agregarblanco.setVisible(false);
        SetImageLabel(usuario, "/imagenes/usuarioblanco.png");
        SetImageLabel(logo, "/imagenes/logoblanco.png");
        SetImageLabel(entrada, "/imagenes/entradaysalida.png");
        SetImageLabel(entradablanco, "/imagenes/entradaysalidablanco.png");
        entradablanco.setVisible(false);
        SetImageLabel(gestion, "/imagenes/gestionar.png");
        SetImageLabel(gestionblanco, "/imagenes/gestionarblanco.png");
        gestionblanco.setVisible(false);
        SetImageLabel(reportes, "/imagenes/reportes.png");
        SetImageLabel(reportesblanco, "/imagenes/reportesblanco.png");
        reportesblanco.setVisible(false);
        SetImageLabel(salir, "/imagenes/cerrarsesion.png");
        SetImageLabel(salirblanco, "/imagenes/cerrarsesionblanco.png");
        salirblanco.setVisible(false);
        // nota: aqui antes existia un "jButtonMenuPrincipal", un boton que
        // nunca se termino de hacer: estaba oculto (setVisible(false)),
        // tenia el texto de relleno "jButton1" que netbeans pone por
        // defecto, y su unica funcion era cerrar la ventana sin volver a
        // abrir el menu principal (el boton "Cancelar" tenia ese mismo bug,
        // ya se arreglo en ControladorGestionInventarioo). como el logo ya
        // hace bien esa funcion, este boton no aportaba nada y se elimino.
    }

    private void SetImageLabel(JLabel label, String root) {
        // antes cada ventana tenia su propio metodo de escalar y todos eran
        // copias del mismo codigo. ahora centralizamos en ImagenUtil.poner
        // que ademas usa escalado por pasos para que los iconos queden mas
        // nitidos, y resuelve el bug de getWidth()==0 antes de pintarse.
        Util.ImagenUtil.poner(label, root, this);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        gestion = new javax.swing.JLabel();
        entrada = new javax.swing.JLabel();
        reportes = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        txtSalir = new javax.swing.JLabel();
        txtGestion = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JLabel();
        txtReporte = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JLabel();
        salirblanco = new javax.swing.JLabel();
        agregarblanco = new javax.swing.JLabel();
        gestionblanco = new javax.swing.JLabel();
        entradablanco = new javax.swing.JLabel();
        reportesblanco = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonEntrada = new javax.swing.JRadioButton();
        jRadioButtonSalida = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelStockActual = new javax.swing.JLabel();
        jLabel11StockDespuesdelMovimiento = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButton1Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelMotivo = new javax.swing.JLabel();
        jComboBoxMotivo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxProductoMongo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldFecha = new javax.swing.JFormattedTextField();
        jLabelcodigoUnico = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVerMovimientos = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        txtSalir1 = new javax.swing.JLabel();
        btnGuardarMovimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 38, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1009, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registros de inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 420, -1));

        menu.setBackground(new java.awt.Color(153, 190, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestion.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entrada.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportes.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setPreferredSize(new java.awt.Dimension(30, 30));
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });
        menu.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtSalir.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(0, 0, 0));
        txtSalir.setText("      Salir del sistema");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSalirMousePressed(evt);
            }
        });
        menu.add(txtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 390, 200, 30));

        txtGestion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtGestion.setForeground(new java.awt.Color(0, 0, 0));
        txtGestion.setText("       Gestión Productos");
        txtGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtGestionMouseExited(evt);
            }
        });
        menu.add(txtGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 230, 30));

        txtEntrada.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtEntrada.setForeground(new java.awt.Color(0, 0, 0));
        txtEntrada.setText("        Gestión Inventario");
        txtEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEntradaMouseExited(evt);
            }
        });
        menu.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, -1));

        txtReporte.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtReporte.setForeground(new java.awt.Color(0, 0, 0));
        txtReporte.setText("        Generar Reportes");
        txtReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReporteMouseExited(evt);
            }
        });
        menu.add(txtReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 180, 230, 20));

        txtAgregar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(0, 0, 0));
        txtAgregar.setText("      Agregar Productos");
        txtAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAgregarMouseExited(evt);
            }
        });
        menu.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 220, 30));

        salirblanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        salirblanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirblancoKeyPressed(evt);
            }
        });
        menu.add(salirblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        menu.add(agregarblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 30));

        gestionblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(gestionblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        entradablanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(entradablanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 126, -1, -1));

        reportesblanco.setPreferredSize(new java.awt.Dimension(30, 30));
        menu.add(reportesblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 174, -1, -1));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 430));

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 140));

        usuario.setBackground(new java.awt.Color(153, 190, 255));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 110, 120));

        jPanel2.setBackground(new java.awt.Color(153, 190, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 25, 51), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de Movimiento ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jRadioButtonEntrada.setBackground(new java.awt.Color(153, 190, 255));
        jRadioButtonEntrada.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jRadioButtonEntrada.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonEntrada.setText("Entrada");
        jRadioButtonEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButtonEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        jRadioButtonSalida.setBackground(new java.awt.Color(153, 190, 255));
        jRadioButtonSalida.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jRadioButtonSalida.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonSalida.setText("Salida");
        jRadioButtonSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Stock Actual");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 365, 130, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Stock despues del Movimiento ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 365, 320, -1));

        jLabelStockActual.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelStockActual.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStockActual.setText(".");
        jPanel2.add(jLabelStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 405, 43, -1));

        jLabel11StockDespuesdelMovimiento.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel11StockDespuesdelMovimiento.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11StockDespuesdelMovimiento.setText(".");
        jPanel2.add(jLabel11StockDespuesdelMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 405, 43, -1));

        jButtonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setBorder(null);
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLimpiarMouseExited(evt);
            }
        });
        jPanel2.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 170, 40));

        jButton1Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButton1Cancelar.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jButton1Cancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButton1Cancelar.setText("Cancelar");
        jButton1Cancelar.setBorder(null);
        jButton1Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1CancelarMouseExited(evt);
            }
        });
        jPanel2.add(jButton1Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 170, 40));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 283, 470, 72));

        jLabelMotivo.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelMotivo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMotivo.setText("Motivo:");
        jPanel2.add(jLabelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 20));

        jComboBoxMotivo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBoxMotivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jComboBoxMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 350, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Detalle (obligatorio solo si el motivo es \"Otro\")");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 258, 400, -1));

        jSpinnerCantidad.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jSpinnerCantidad.setBorder(null);
        jSpinnerCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 350, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Unidades");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 100, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 20));

        jComboBoxProductoMongo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProductoMongo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxProductoMongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductoMongoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxProductoMongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 350, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Producto:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Código del Producto");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 210, -1));

        jFormattedTextFieldFecha.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldFecha.setBorder(null);
        jFormattedTextFieldFecha.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedTextFieldFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldFecha.setText("DD/MM/AA");
        jPanel2.add(jFormattedTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 90, -1));

        jLabelcodigoUnico.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabelcodigoUnico.setForeground(new java.awt.Color(0, 0, 0));
        jLabelcodigoUnico.setText(".");
        jPanel2.add(jLabelcodigoUnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 120, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 67, -1));

        btnVerMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        btnVerMovimientos.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        btnVerMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        btnVerMovimientos.setText("Ver Movimientos");
        btnVerMovimientos.setBorder(null);
        btnVerMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerMovimientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerMovimientosMouseExited(evt);
            }
        });
        btnVerMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMovimientosActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 690, 500));

        header.setBackground(new java.awt.Color(0, 38, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 38, 102));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        txtSalir1.setBackground(new java.awt.Color(0, 38, 102));
        txtSalir1.setFont(new java.awt.Font("Roboto Condensed Black", 0, 24)); // NOI18N
        txtSalir1.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir1.setText("X");
        txtSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalir1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalir1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 946, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 50));

        btnGuardarMovimiento.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarMovimiento.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        btnGuardarMovimiento.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarMovimiento.setText("Guardar Movimiento");
        btnGuardarMovimiento.setBorder(null);
        btnGuardarMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMovimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMovimientoMouseExited(evt);
            }
        });
        btnGuardarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMovimientoActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cerrarSesion() {
        Vista.FrmLogin login = new Vista.FrmLogin();
        Modelo.LoginDAO loginDao = new Modelo.LoginDAO();
        new Controlador.ControladorLogin(login, loginDao);
        login.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }


    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        cerrarSesion();
    }//GEN-LAST:event_salirKeyPressed

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked

    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        txtSalir.setForeground(Color.white);
        salir.setVisible(false);
        salirblanco.setVisible(true);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        txtSalir.setForeground(Color.black);
        salirblanco.setVisible(false);
        salir.setVisible(true);
    }//GEN-LAST:event_txtSalirMouseExited

    private void txtSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMousePressed
        cerrarSesion();
    }//GEN-LAST:event_txtSalirMousePressed

    private void txtGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseClicked
         FrmGestionProductos vistaInvProd = new FrmGestionProductos();

    ProductoDAO daoProducto = new ProductoDAO();
    new ControladorGestionP(vistaInvProd, daoProducto);

    vistaInvProd.setLocationRelativeTo(null);
    vistaInvProd.setVisible(true);

    this.dispose();
                
    }//GEN-LAST:event_txtGestionMouseClicked

    private void txtGestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseEntered
        txtGestion.setForeground(Color.white);
        gestion.setVisible(false);
        gestionblanco.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseEntered

    private void txtGestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionMouseExited
        txtGestion.setForeground(Color.black);
        gestionblanco.setVisible(false);
        gestion.setVisible(true);
    }//GEN-LAST:event_txtGestionMouseExited

    private void txtEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseClicked
        
    }//GEN-LAST:event_txtEntradaMouseClicked

    private void txtEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseEntered
        txtEntrada.setForeground(Color.white);
        entrada.setVisible(false);
        entradablanco.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseEntered

    private void txtEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaMouseExited
        txtEntrada.setForeground(Color.black);
        entradablanco.setVisible(false);
        entrada.setVisible(true);
    }//GEN-LAST:event_txtEntradaMouseExited

    private void txtReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseClicked
        Vista.FrmGenerarReporte vista = new Vista.FrmGenerarReporte();
        Modelo.MovimientoDAO movDao = new Modelo.MovimientoDAO();
        Modelo.ProductoDAO prodDao = new Modelo.ProductoDAO();
        new Controlador.ControladorGenerarReporte(vista, movDao, prodDao);
        vista.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtReporteMouseClicked

    private void txtReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseEntered
        txtReporte.setForeground(Color.white);
        reportes.setVisible(false);
        reportesblanco.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseEntered

    private void txtReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporteMouseExited
        txtReporte.setForeground(Color.black);
        reportesblanco.setVisible(false);
        reportes.setVisible(true);
    }//GEN-LAST:event_txtReporteMouseExited

    private void txtAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseClicked
        FrmProducto vistaAgProd = new FrmProducto();
        vistaAgProd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ProductoDAO daoProducto = new ProductoDAO();
        new ControladorProducto(vistaAgProd, daoProducto);
        vistaAgProd.setVisible(true);
        vistaAgProd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_txtAgregarMouseClicked

    private void txtAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseEntered
        txtAgregar.setForeground(Color.white);
        agregar.setVisible(false);
        agregarblanco.setVisible(true);
    }//GEN-LAST:event_txtAgregarMouseEntered

    private void txtAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseExited
        txtAgregar.setForeground(Color.black);
        agregar.setVisible(true);
        agregarblanco.setVisible(false);
    }//GEN-LAST:event_txtAgregarMouseExited

    private void salirblancoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirblancoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirblancoKeyPressed

    private void jComboBoxProductoMongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductoMongoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProductoMongoActionPerformed

    private void txtSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalir1MouseClicked

    private void txtSalir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_txtSalir1MouseEntered

    private void txtSalir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalir1MouseExited

        int rgb = Color.HSBtoRGB(217 / 360f, 100 / 100f, 40 / 100f);
        btnSalir.setBackground(new Color(rgb));
    }//GEN-LAST:event_txtSalir1MouseExited

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnGuardarMovimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMovimientoMouseEntered
        btnGuardarMovimiento.setBackground(new Color(82,126,204));
        btnGuardarMovimiento.setForeground(Color.white);
    }//GEN-LAST:event_btnGuardarMovimientoMouseEntered

    private void btnGuardarMovimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMovimientoMouseExited
        btnGuardarMovimiento.setBackground(Color.white);
        btnGuardarMovimiento.setForeground(Color.black);
    }//GEN-LAST:event_btnGuardarMovimientoMouseExited

    private void jButtonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarMouseEntered
        jButtonLimpiar.setBackground(new Color(82,126,204));
        jButtonLimpiar.setForeground(Color.white);
    }//GEN-LAST:event_jButtonLimpiarMouseEntered

    private void jButtonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarMouseExited
        jButtonLimpiar.setBackground(Color.white);
        jButtonLimpiar.setForeground(Color.black);
    }//GEN-LAST:event_jButtonLimpiarMouseExited

    private void jButton1CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1CancelarMouseEntered
        jButton1Cancelar.setBackground(new Color(82,126,204));
        jButton1Cancelar.setForeground(Color.white);
    }//GEN-LAST:event_jButton1CancelarMouseEntered

    private void jButton1CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1CancelarMouseExited
        jButton1Cancelar.setBackground(Color.white);
       jButton1Cancelar.setForeground(Color.black);
    }//GEN-LAST:event_jButton1CancelarMouseExited

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        FrmSistema frmSistema = new FrmSistema();
frmSistema.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
frmSistema.setVisible(true);
frmSistema.setLocationRelativeTo(null);
this.dispose();
    }//GEN-LAST:event_logoMouseClicked

    private void btnVerMovimientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMovimientosMouseEntered
        btnVerMovimientos.setBackground(new Color(82,126,204));
        btnVerMovimientos.setForeground(Color.white);
    }//GEN-LAST:event_btnVerMovimientosMouseEntered

    private void btnVerMovimientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMovimientosMouseExited
        btnVerMovimientos.setBackground(Color.white);
        btnVerMovimientos.setForeground(Color.black);
    }//GEN-LAST:event_btnVerMovimientosMouseExited

    private void btnVerMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMovimientosActionPerformed
        // este es el punto de entrada a la ventana nueva de "ver movimientos".
        // sigue el mismo patron de navegacion que el resto de la app: se abre
        // la pantalla nueva y se cierra esta.
        FrmGestionMovimientos vistaMovs = new FrmGestionMovimientos();
        vistaMovs.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Modelo.MovimientoDAO movimientoDao = new Modelo.MovimientoDAO();
        new Controlador.ControladorGestionMovimientos(vistaMovs, movimientoDao);
        vistaMovs.setVisible(true);
        vistaMovs.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVerMovimientosActionPerformed

    private void btnGuardarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMovimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionInventarioo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregar;
    private javax.swing.JLabel agregarblanco;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel entrada;
    private javax.swing.JLabel entradablanco;
    private javax.swing.JLabel gestion;
    private javax.swing.JLabel gestionblanco;
    private javax.swing.JPanel header;
    public javax.swing.JButton jButton1Cancelar;
    public javax.swing.JButton btnGuardarMovimiento;
    public javax.swing.JButton btnVerMovimientos;
    public javax.swing.JButton jButtonLimpiar;
    public javax.swing.JComboBox<String> jComboBoxProductoMongo;
    public javax.swing.JFormattedTextField jFormattedTextFieldFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11StockDespuesdelMovimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelMotivo;
    public javax.swing.JComboBox<String> jComboBoxMotivo;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelStockActual;
    public javax.swing.JLabel jLabelcodigoUnico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRadioButtonEntrada;
    public javax.swing.JRadioButton jRadioButtonSalida;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner jSpinnerCantidad;
    public javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel reportes;
    private javax.swing.JLabel reportesblanco;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel salirblanco;
    private javax.swing.JLabel txtAgregar;
    private javax.swing.JLabel txtEntrada;
    private javax.swing.JLabel txtGestion;
    private javax.swing.JLabel txtReporte;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JLabel txtSalir1;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
