package Vista;

import Modelo.Producto;
import Modelo.ProductoDAO;

/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmEditaPrduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEditaPrduct.class.getName());
    private ProductoDAO dao;
    private String originalNombre;
    private Runnable onSave;

    /**
     * Creates new form FrmEditaPrduct
     */
    public FrmEditaPrduct() {
        initComponents();
        jLabelCodigoProducto = new javax.swing.JLabel();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        jLabelCodigoProducto.setText("Código");
    }

    public FrmEditaPrduct(Producto producto, ProductoDAO dao, Runnable onSave) {
        initComponents();
        this.dao = dao;
        this.onSave = onSave;
        System.out.println("FrmEditaPrduct.<init> -> producto recibido: " + (producto != null ? producto.getNombre() : "null"));
        cargarProducto(producto);
        System.out.println("FrmEditaPrduct.<init> -> after cargarProducto, originalNombre=" + originalNombre);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1Nombre = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelPrecioUnitario = new javax.swing.JLabel();
        jLabelTipoProveedor = new javax.swing.JLabel();
        jLabelTipoStock = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldPrecioUnitario = new javax.swing.JTextField();
        jTextFieldProveedor = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jButtonGuardarCambios = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelMuestraNombredeproducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1Nombre.setText("Nombre");

        jLabelTipo.setText("Tipo");

        jLabelPrecioUnitario.setText("Precio Unitario");

        jLabelTipoProveedor.setText("Proveedor");

        jLabelTipoStock.setText("Stock");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lacteos", "limpieza", "snacks", "embutidos", "carnes", "otros", "condimentos" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jTextFieldPrecioUnitario.setText("jTextField1");

        jTextFieldProveedor.setText("jTextField1");

        jTextFieldStock.setText("jTextField1");

        jButtonGuardarCambios.setText("Guardar Cambios");
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelMuestraNombredeproducto.setText(".");

        jLabel1.setText("EDITAR PRODUCTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonGuardarCambios)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelTipoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrecioUnitario)
                    .addComponent(jTextFieldProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jLabelMuestraNombredeproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Nombre)
                            .addComponent(jLabelMuestraNombredeproducto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipo)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecioUnitario)
                            .addComponent(jTextFieldPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoProveedor)
                            .addComponent(jTextFieldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTipoStock)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarCambios)
                    .addComponent(jButtonCancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        System.out.println("FrmEditaPrduct.jButtonGuardarCambiosActionPerformed -> clicked");
        guardarCambios();
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProductosActionPerformed
        // Product selector removed. Action no longer needed.
    }//GEN-LAST:event_jComboBoxProductosActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // No action needed for type selection here.
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEditaPrduct().setVisible(true));
    }

    private void cargarProductos() {
        // Method removed: product selector UI was deleted per user request.
    }

    private void cargarProducto(Producto producto) {
        if (producto == null) {
            System.out.println("FrmEditaPrduct.cargarProducto -> producto es null");
            return;
        }
        System.out.println("FrmEditaPrduct.cargarProducto -> cargando producto: " + producto.getNombre());
        jLabelMuestraNombredeproducto.setText(producto.getNombre());
        try {
            jComboBoxTipo.setSelectedItem(producto.getTipo());
        } catch (Exception ex) {
            System.out.println("FrmEditaPrduct.cargarProducto -> error al setear tipo: " + ex.getMessage());
        }
        jTextFieldPrecioUnitario.setText(String.valueOf(producto.getPrecioUnit()));
        jTextFieldProveedor.setText(producto.getProveedor());
        jTextFieldStock.setText(String.valueOf(producto.getStock()));
        if (jTextFieldCodigoProducto != null) {
            jTextFieldCodigoProducto.setText(producto.getCodigo() == null ? "" : producto.getCodigo());
        }
        originalNombre = producto.getNombre();
    }

    private void guardarCambios() {
        try {
            String nombre = jLabelMuestraNombredeproducto.getText().trim();
            String tipo = jComboBoxTipo.getSelectedItem().toString();
            String precioText = jTextFieldPrecioUnitario.getText().trim().replace(',', '.');
            String proveedor = jTextFieldProveedor.getText().trim();
            String stockText = jTextFieldStock.getText().trim();
            String codigo = jTextFieldCodigoProducto != null ? jTextFieldCodigoProducto.getText().trim() : "";

            if (nombre.isBlank() || precioText.isBlank() || proveedor.isBlank() || stockText.isBlank()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos para guardar.");
                return;
            }

            double precio = Double.parseDouble(precioText);
            int stock = Integer.parseInt(stockText);

            Modelo.Producto actualizado = new Modelo.Producto(nombre, tipo, precio, proveedor, stock, codigo);
            System.out.println("FrmEditaPrduct.guardarCambios -> originalNombre: " + originalNombre);
            System.out.println("FrmEditaPrduct.guardarCambios -> actualizado: " + actualizado.getNombre() + ", tipo=" + actualizado.getTipo() + ", precio=" + actualizado.getPrecioUnit() + ", proveedor=" + actualizado.getProveedor() + ", stock=" + actualizado.getStock() + ", codigo=" + actualizado.getCodigo());
            dao.modificarProducto(originalNombre, actualizado);
            System.out.println("FrmEditaPrduct.guardarCambios -> llamado a dao.modificarProducto");
            javax.swing.JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");
            if (onSave != null) {
                onSave.run();
            }
            dispose();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Precio o stock inválido. Use valores numéricos.");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Nombre;
    private javax.swing.JLabel jLabelMuestraNombredeproducto;
    private javax.swing.JLabel jLabelPrecioUnitario;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoProveedor;
    private javax.swing.JLabel jLabelTipoStock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPrecioUnitario;
    private javax.swing.JTextField jTextFieldProveedor;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JLabel jLabelCodigoProducto;
    private javax.swing.JTextField jTextFieldCodigoProducto;
    // End of variables declaration//GEN-END:variables
}
